jobs:
  include:
    - stage: "Test"
      name: "Lint"
      language: node_js
      before_install:
        - sudo apt-get install -y xmlstarlet
      node_js: 8
      script:
        - xmlstarlet validate --well-formed icons/*.svg
        - npm run jsonlint
        - npm run svglint
    - name: "Build website"
      language: ruby
      rvm: 2.4.1
      install:
        - gem install jekyll
      script:
        - jekyll build
    - name: "Test package"
      language: node_js
      node_js: 8
      script:
        - npm run test

    - stage: deploy
      name: "NPM Package"
      language: node_js
      node_js: 8
      if: branch = master

      deploy:
        provider: npm
        email: "johanringmann@gmail.com"
        api_key: "$NPM_KEY"
        on:
          branch: master

notifications:
  email:
    on_success: never
    on_failure: change
